name: financial_wellbeing
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

#Network
  http: ^1.2.2
  connectivity_plus: ^6.1.0
  cached_network_image: ^3.4.1

#local storage
  get_storage: ^2.1.1
  shared_preferences: ^2.3.3

# state clean_architecture_with_state_management:
  get: ^4.6.6
  go_router: ^14.6.0

#data
  intl: ^0.19.0

# url_launcher:
  url_launcher: ^6.3.1


#assets
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  flutter_svg: ^2.0.14







cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
    - assets/images/
    - assets/fonts/
    - assets/fonts/Plus_Jakarta_Sans/static/



  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-ExtraBold.ttf
          weight: 800
#        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Black.ttf
#          weight: 900
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-ExtraLight.ttf
          weight: 200
#        - asset: assets/fonts/Plus_Jakarta_Sans/static/PlusJakartaSans-Thin.ttf
#          weight: 100


